from collections.abc import Sequence

class Pane:
    @property
    def pane_id(self) -> str: ...
    @property
    def window(self) -> Window: ...
    def select(self) -> None: ...
    def resize(self, *, zoom: bool = ...) -> None: ...

class Window:
    @property
    def panes(self) -> Sequence[Pane]: ...
    def split(self, *, direction: object = ..., shell: str = ...) -> Pane: ...

class Session:
    @property
    def windows(self) -> Sequence[Window]: ...

class Server:
    def __init__(self) -> None: ...
    @property
    def sessions(self) -> Sequence[Session]: ...
